[phases.setup]
nixPkgs = ["chromium", "nss", "atk", "cups", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "xorg.libXcursor", "xorg.libXi", "xorg.libXtst", "pango", "cairo", "alsa-lib"]

[start]
cmd = "node index.js"
